version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hostel-backend-node-container
    ports:
      - "3000:3000"
    environment:
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      MONGODB_URL: ${MONGODB_URL}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      TRANSPORTER_USERNAME: ${TRANSPORTER_USERNAME}
      TRANSPORTER_PASSWORD: ${TRANSPORTER_PASSWORD}
      RAZORPAY_API_SECRET: ${RAZORPAY_API_SECRET}
      RAZORPAY_API_ID: ${RAZORPAY_API_ID}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      FRONT_END_URL: ${FRONT_END_URL}
    networks:
      - default

  caddy:
    image: caddy:latest
    container_name: caddy-container
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default

volumes:
  caddy_data:
  caddy_config:
