name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t hostel-backend-node-image .

      - name: Stop previous container (if exists)
        run: docker stop hostel-backend-node-container || true

      - name: Remove previous container (if exists)
        run: docker rm hostel-backend-node-container || true

      - name: Run Docker container
        run: docker run -d --name hostel-backend-node-container -p 3000:3000 hostel-backend-node-image
