name: Deploy Node.js App with Docker Compose (Self-hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      TRANSPORTER_USERNAME: ${{ secrets.TRANSPORTER_USERNAME }}
      TRANSPORTER_PASSWORD: ${{ secrets.TRANSPORTER_PASSWORD }}
      RAZORPAY_API_SECRET: ${{ secrets.RAZORPAY_API_SECRET }}
      RAZORPAY_API_ID: ${{ secrets.RAZORPAY_API_ID }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      FRONT_END_URL: ${{ secrets.FRONT_END_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if Docker Compose is installed
        run: docker-compose version

      - name: Stop and remove previous containers if they exist
        run: |
          docker-compose down --remove-orphans
          docker rm -f hostel-backend-node-container || true
          docker rm -f caddy-container || true

      - name: Pull Docker images (if needed)
        run: docker-compose pull

      - name: Build and start Docker Compose services
        run: |
          docker-compose up -d --build
